name: ESP32 CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    branches:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare Checkout 
      uses: actions/checkout@v3
      with:
          submodules: "recursive"
    - name: Install Python 
      uses: actions/setup-python@v3
      with:
          python-version: "3.9"
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build PlatformIO Project
      run: pio run --project-dir="Firmware_Wortuhr"
